language: csharp
solution: xBudget.CeiCrawler/xBudget.CeiCrawler.sln
mono: none
dotnet: 3.1.302
script:
  - dotnet restore xBudget.CeiCrawler/xBudget.CeiCrawler.sln
  - dotnet build xBudget.CeiCrawler/xBudget.CeiCrawler.sln
  - dotnet test xBudget.CeiCrawler/xBudget.CeiCrawler.sln --no-build /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
after_script:
    - bash <(curl -s https://codecov.io/bash)